<?php

use Aalaap\Hashapass\Hashapass;
 
class HashapassTest extends \PHPUnit_Framework_TestCase {
 
  public function testHashapassGeneratesCorrectPasswordOfDefaultLength()
  {
    $hashapass = new Hashapass();
    
    $this->assertEquals('7/KxvM4S', $hashapass->generate('master', 'parameter'),
      'Default-length Password generated by Hashapass->generate was not correct.');
  }

  public function testHashapassGeneratesCorrectPasswordOfCustomLength()
  {
    $hashapass = new Hashapass();
    
    $this->assertEquals('7/KxvM4S+1veNznd', $hashapass->generate('master', 'parameter', 16),
      'Custom-length Password generated by Hashapass->generate was not correct.');
  }

}