<?php

/**
 * Hashapass PHPUnit test class file
 *
 * PHP version 5
 *
 * @category Class
 * @package  Hashapass
 * @author   Aalaap Ghag <aalaap@gmail.com>
 * @license  http://www.wtfpl.net/txt/copying WTFPL
 * @link     https://github.com/aalaap/Hashapass
 */ 

use Aalaap\Hashapass\Hashapass;

/**
 * Hashapass PHPUnit test class
 *
 * The class holding the Hashapass PHPUnit test class definition
 *
 * @category Class
 * @package  Hashapass
 * @author   Aalaap Ghag <aalaap@gmail.com>
 * @license  http://www.wtfpl.net/txt/copying WTFPL
 * @link     https://github.com/aalaap/Hashapass
 */ 
class HashapassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Asserts that the generate function returns a valid password
     * of the default length, i.e. 8 characters. 
     *
     * @return void
     */
    public function testHashapassGeneratesCorrectPasswordOfDefaultLength()
    {
        $hashapass = new Hashapass();
    
        $this->assertEquals(
            '7/KxvM4S', $hashapass->generate('master', 'parameter'),
            'Default-length Password generated by Hashapass->generate was not'.
            ' correct.'
        );
    }

    /**
     * Asserts that the generate function returns a valid password
     * of a custom length when specified. 
     *
     * @return void
     */
    public function testHashapassGeneratesCorrectPasswordOfCustomLength()
    {
        $hashapass = new Hashapass();
    
        $this->assertEquals(
            '7/KxvM4S+1veNznd', $hashapass->generate('master', 'parameter', 16),
            'Custom-length Password generated by Hashapass->generate was not'.
            ' correct.'
        );
    }
}