<?php

use Aalaap\Hashapass\Hashapass;
 
class HashapassTest extends \PHPUnit_Framework_TestCase {
 
  public function testHashapassGeneratesCorrectPassword()
  {
    $hashapass = new Hashapass();
    
    $this->assertEquals('7/KxvM4S', $hashapass->generate('master', 'parameter'), 'Password generated by Hashapass->generate was not correct.');
  }
}